### ISSUE TITLE
Return type when starting a component

### ISSUE THREAD

**Issue by pukkamustard** [anmonteiro/archi#18]
Just an idea.

Currently components are started with a function `start` with signature `'ctx -> ('a, [ 'Msg of string ]) result Io.t`.

Would it make sense to instead use `'ctx -> ('a, exn) result Io.t`. This would allow failures to be reported more expressively with OCaml exceptions.

For messages one could use `Failure` and a custom exception could be defined by Archi to indicate cycles (currently `'Cycle_found`).

I might be able to provide patches if this makes sense and would be a welcome change.

Thanks!

**Comment by anmonteiro** [comment]
> Would it make sense to instead use `'ctx -> ('a, exn) result Io.t`.

how about `'ctx -> ('a, [ > `Msg of string | `Exn of exn] ) result Io.t.`?

**Comment by pukkamustard** [comment]
> how about `` 'ctx -> ('a, [ > `Msg of string | `Exn of exn] ) result Io.t `` ?

Hm, I still prefer `'ctx -> ('a, exn) result Io.t`.

One reason for using just `exn` as error type is that it would compose nicely with `Lwt_result.catch`.

For example:

```
let start (configuration : Configuration.t) =
  Client.start configuration
  |> Lwt_result.catch
  |> Result.map_error (fun exn ->  `Msg (Printexc.to_string exn))
```

becomes

```
let start (configuration : Configuration.t) =
  Client.start configuration
  |> Lwt_result.catch
```

**Comment by pukkamustard** [comment]
Not really an issue. Closing.
